<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE elements [
        <!ELEMENT elements (element)*>
        <!ELEMENT element (title|price|location|engine|description|mileage|transmission)*>
        <!ATTLIST element
                id CDATA #REQUIRED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT location (#PCDATA)>
        <!ELEMENT engine (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT mileage (#PCDATA)>
        <!ELEMENT transmission (#PCDATA)>
        ]>
<elements>
    <element id="1">
        <title>Ford Focus ST 2016</title>
        <price>16 000</price>
        <location>Днепр (Днепропетровск)</location>
        <engine>Бензин, 2 л.</engine>
        <description>72 тыс. км Днепр (Днепропетровск) Бензин, 2 л. Ручная / Механика оригинал СТ, 260 лошадей, механика
            6 ступ.
            вся в оригинале
            крашено 2 бампера, больше ничего
            состояние идеал!
            дора
            ботаный выхлоп и впуск- звучит невероятно красиво!!!
            это самый топовый СТ с мулитедиа на синк3 - полностью русифицировано- есть карплей, андроид авто.
            салон Рекаро кожа +ткань,
            фары поворотные ксенон +лед

            авто полночтью растаможено и сертифицировано,
            весь пакет документов,

            осталось поставить на учет - в стоимость входиь постановка автомобиля на учет и переоформление на нового
            владельца
            ...
        </description>
        <mileage>72 тыс. км</mileage>
        <transmission>Ручная / Механика</transmission>
    </element>
    <element id="2">
        <title>Ford Fusion se 2016</title>
        <price>15 100</price>
        <location>Малин</location>
        <engine>Бензин, 2.5 л.</engine>
        <description>44 тыс. км Малин Бензин, 2.5 л. Автомат 3FA6P0H7хGRхххх32 Проверено AUTO.RIA по реестрам МВД: дата
            последней операции, розыск, марка/модель, год, двигатель, цвет. Авто покупалось для себя,без пробега по
            Украине, не крашеная родная трехслойна краска ,оригинальный пробег,цвет красивый играет на солнце,есть фото
            со штатов,состояние идеальное,реальному покупателю торг ...
        </description>
        <mileage>44 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="3">
        <title>Ford Fiesta 2018</title>
        <price>11 300</price>
        <location>Одесса</location>
        <engine>Бензин, 1.6 л.</engine>
        <description>16 тыс. км Одесса Бензин, 1.6 л. Автомат BH 2764 MO AUTO.RIA распознал гос.номер авто по фото
            3FADP4BJхJMхххх48 Проверено AUTO.RIA по реестрам МВД: дата последней операции, розыск, марка/модель, год,
            двигатель, цвет. ...
        </description>
        <mileage>16 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="4">
        <title>Ford Focus SE+ 2017</title>
        <price>9 999</price>
        <location>Никополь</location>
        <engine>Бензин, 1 л.</engine>
        <description>9 тыс. км Никополь Бензин, 1 л. Автомат KA 9579 AC AUTO.RIA распознал гос.номер авто по фото
            1FADP3FEхJLхххх36 Проверено AUTO.RIA по реестрам МВД: дата последней операции, розыск, марка/модель, год,
            двигатель, цвет. Авто в идеале! пробег 8тыс ( новая машина) Очень хорошая комплектация включая зимний пакет
            . Регистрация в украине 27.02.2020 сделано 1рвое ТО на Официале . замена всех фильтров и жидкостей ,
            диагностика ходовой и т.д !!!!!! Машина не битая и не утоплиник !!!!! замена правой пассажирской двери!!!!
            больше не чего !!!! машина снята с киевского учёта и поставленна в никополе ! новый номер АЕ 2334 МI
            ...
        </description>
        <mileage>9 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="5">
        <title>Ford Fusion SE 2019</title>
        <price>17 300</price>
        <location>Одесса</location>
        <engine>Бензин, 2.5 л.</engine>
        <description>14 тыс. км Одесса Бензин, 2.5 л. Автомат 3FA6P0H7хKRхххх70 Проверено AUTO.RIA по реестрам МВД: дата
            последней операции, розыск, марка/модель, год, двигатель, цвет. Новое Авто, рейсталинг, дата производства
            март 2019 г., мощный и надежный двигатель 2.5 л.,заменены все фильтра и масла.,богатая комплектация SE,
            большой монитор, ассистент полос, датчик света, датчики мертвых зон, парктроники, камера заднего вида,
            двухзонный климат контроль, и многое другое!!! Идеальное состояние!!!Проверка на любом СТО за Ваш счёт!!!
            Обмен не интересует!!! ...
        </description>
        <mileage>14 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="6">
        <title>Ford Focus ***LIFT***IDEAL*** 2015</title>
        <price>9 450</price>
        <location>Стрый</location>
        <engine>Дизель, 1.5 л.</engine>
        <description>158 тыс. км Стрый Дизель, 1.5 л. Ручная / Механика ВАРТУЄ УВАГИ!!!
            Жоден болтик не кручений !
            6 -ти ступка!!
            Всі вікна рідні!
            Кузов без сколів , реально як нова машина!!
            Мотор, ходова все супер!
            Салон в ідеальному стані !
            Дуже економне авто!!
            Любий вид переоформлення!!!
            ...
        </description>
        <mileage>158 тыс. км</mileage>
        <transmission>Ручная / Механика</transmission>
    </element>
    <element id="7">
        <title>Ford Fusion titanium 2016</title>
        <price>15 000</price>
        <location>Бердичев</location>
        <engine>Газ/бензин, 2.5 л.</engine>
        <description>130 тыс. км Бердичев Газ/бензин, 2.5 л. Типтроник AM 5940 EA AUTO.RIA распознал гос.номер авто по
            фото 3FA6P0H7хGRхххх50 Проверено AUTO.RIA по реестрам МВД: дата последней операции, розыск, марка/модель,
            год, двигатель, цвет. Продаю свой автомобиль в связи с покупкою нового авто. Машина в прекрасному состояние.
            В експлуатации с 2017г. Обслуживалась исключительно на Ford Winner (есть все сервисние ТО и сервисная
            документация). Автомобиль полностью обслужено, последнее ТО на 128 000. Вся световая сигнализация, впереди и
            сзади и включая противотуманние фари - светодиодная. Автомобиль покрит бронепленкой от сколов на 30% кузова.
            Установлено у официального дилера компании Ford и зарегистрирована в тех. паспорте газове оборудование
            (LPG). В машине новий АКБ, два комплекта резини, хром пакет включая зашиту колесних арок, подогрев сидений,
            електро регулировки сидений и зеркал, русифицирований большой мультимедийний дисплей и компьютер. Салон
            кожна и алькантара. Безключевой доступ и система отдаленного запуска двигателя с автоматичним прогресом
            сидушек и всего салонах в зимнее врем'я года. Датчик Света и светодиодние ходових огни. Кожаний руль, 10
            подушек безопасности. Очень тихий и легкий на движения автомобиль. Дорогая газовая установка с расходом 7л.
            на трасе и 11л. в городе видает 178л.с. Полноразмерная запаска и все четире колеса на оригінальних родних
            18-и дюймових титанах. Приветствую осмотр на любом СТО включая официального Ford Winner. Навигация,
            двухзонний климат-контроль, музика и развлечения - на русском и работают изумительно хорошо. Коробка автомат
            с режимом Sport, переключатися незаметно. Електроручник. Качественная тонировка всех стекол. Громкая связь,
            блютуз, круиз, лимит-контроль и все остальное присутствует и четко работает на мультируле затянутом в кожу.
            В машине присутствует камера заднього виду и парковочная система. Буду рад ответить на все Ваши вопроси.
            Торг возможен до Вашей победи и обоюдного соглашения. ...
        </description>
        <mileage>130 тыс. км</mileage>
        <transmission>Типтроник</transmission>
    </element>
    <element id="8">
        <title>Ford Fusion 2017</title>
        <price>17 600</price>
        <location>Харьков</location>
        <engine>Гибрид, 2 л.</engine>
        <description>80 тыс. км Харьков Гибрид, 2 л. Вариатор Продам Ford Fusion Hybrid SE 2017 Электро двигатель + ДВС
            , Система start/stop . Автомобиль в идеальном состоянии. Ни одна деталь не крашена, вся безопасность целая.
            Обслужен и никаких вложений не требует. Очень экономичный и динамичный двигатель. Расход: Город - 5 л,
            Трасса - 5.5 л/100км. Фары и противотуманки LED. Датчик света, Датчик дождя, Климат контроль, Кнопка
            Старт/Стоп, Круиз контроль, Мульти руль, камера заднего вида, Мультимедиа SYNC 12 динамиков, Диски R18. Все
            вопросы по телефону. ...
        </description>
        <mileage>80 тыс. км</mileage>
        <transmission>Вариатор</transmission>
    </element>
    <element id="9">
        <title>Ford Fusion Ford Fusion HYBRID 2017</title>
        <price>19 700</price>
        <location>Одесса</location>
        <engine>Гибрид, 2 л.</engine>
        <description>75 тыс. км Одесса Гибрид, 2 л. Автомат 3FA6P0RUхHRхххх55 Проверено AUTO.RIA по реестрам МВД: дата
            последней операции, розыск, марка/модель, год, двигатель, цвет. Ford Fusion TITANIUM HYBRID 2017! СОСТОЯНИЕ
            НОВОГО АВТО! ПОЛНАЯ КОМПЛЕКТАЦИЯ! Натуральная кожа с подогревом и вентиляцией сидений Память сидений Full
            LED Сенсор дождя Датчики давления воздуха в шинах Система бесключевого доступа Система мониторинга слепых
            зон Камера заднего вида Audio system SONY Диски R18 Новая резина MICHELIN Полностью обслужен! Защита
            двигателя. Расход топлива на 100км - 5л ...
        </description>
        <mileage>75 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="10">
        <title>Ford Fiesta 2016</title>
        <price>12 000</price>
        <location>Киев</location>
        <engine>Бензин, 1 л.</engine>
        <description>6 тыс. км Киев Бензин, 1 л. Автомат ...</description>
        <mileage>6 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="11">
        <title>Ford Fusion S 2015</title>
        <price>10 680</price>
        <location>Киев</location>
        <engine>Бензин, 2.5 л.</engine>
        <description>73 тыс. км Киев Бензин, 2.5 л. Типтроник KA 7417 AC AUTO.RIA распознал гос.номер авто по фото
            3FA6P0G7хFRхххх47 Проверено AUTO.RIA по реестрам МВД: дата последней операции, розыск, марка/модель, год,
            двигатель, цвет. Предлагаю ВАМ комфортабельный и роскошный автомобиль Ford Fusion , в шикарном вишневом
            цвете(дата производства 04 2015) с очень надежным атмосферным мотором 2.5 на который при желании
            устанавливается ГБО. Растаможен и поставлен на украинский учет. Пробег на момент покупки 44280 миль. Авто НЕ
            ТРЕБУЕТ никаких дополнительный вложений по технической части, сел и поехал. ТОРГ ОБЯЗАТЕЛЕН, НО ТОЛЬКО У
            КАПОТА АВТО. ...
        </description>
        <mileage>73 тыс. км</mileage>
        <transmission>Типтроник</transmission>
    </element>
    <element id="12">
        <title>Ford Focus 2017</title>
        <price>11 500</price>
        <location>Хмельницкий</location>
        <engine>1.6 л.</engine>
        <description>42 тыс. км Хмельницкий 1.6 л. Ручная / Механика Продаю власний автомобіль, бережна експлуатація,
            гаражне зберігання, без підкрасів, сервісні книжка, куплявся січень 2017р.,надійна, економія, все працює
            справно, будь які перевірки, тонування ,встановлено металевий захист мотора і кпп,зроблено ТО 3.два
            комплекти шин! авто варте уваги, торг біля машини! ...
        </description>
        <mileage>42 тыс. км</mileage>
        <transmission>Ручная / Механика</transmission>
    </element>
    <element id="13">
        <title>Ford Edge SEL 2017</title>
        <price>22 900</price>
        <location>Полтава</location>
        <engine>Бензин, 2 л.</engine>
        <description>20 тыс. км Полтава Бензин, 2 л. Автомат 2FMPK4J9хHBхххх78 Проверено AUTO.RIA по реестрам МВД: дата
            последней операции, розыск, марка/модель, год, двигатель, цвет. Автомобиль покупал для себя. Денег на авто
            не жалел. Салон аккуратный, ухоженный, снаружи также все без сколов и царапин. Не гремит не скрипит.
            Сенсорный экран, SYNC 3 не виснет . Поддерживает карплей, андроид ауто, подключение через блютуз. Камера
            заднего вида, датчик слепых зон, парктроник - очень удобно парковаться. Кожаный салон, сидения не
            затасканные. Полный привод. Коробка автомат. Автомобиль очень комфортный! (Интересен обмен на авто дороже, с
            моей доплатой ) ...
        </description>
        <mileage>20 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="14">
        <title>Ford Focus 2017</title>
        <price>12 700</price>
        <location>Киев</location>
        <engine>Бензин, 2.01 л.</engine>
        <description>20 тыс. км Киев Бензин, 2.01 л. Автомат BA 4490 BX AUTO.RIA распознал гос.номер авто по фото
            1FADP3H2хHLхххх30 Проверено AUTO.RIA по реестрам МВД: дата последней операции, розыск, марка/модель, год,
            двигатель, цвет. Автомобиль в идеальном состоянии и максимальной комплектации (кроме кожи). Премиум акустика
            SONY , сабвуфер, LED оптика, подогрев руля, автозапуск, сенсорный дисплей, парктроники, камера заднего вида
            с динамической разметкой, атмосферная подсветка салона с возможностью изменения цветов, датчики давления в
            шинах... ...
        </description>
        <mileage>20 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="15">
        <title>Ford Focus 1.5 AT (120 л.с.) 2019</title>
        <price>21 146</price>
        <location>Житомир</location>
        <engine>Бензин, 1.5 л.</engine>
        <description>без пробега Житомир Бензин, 1.5 л. Автомат Ціна вказана з доплатою за колір.
            Комплектація:
            -клімат контроль
            -шкіряне оздоблення керма,рукоятки важеля коробки передач
            -радіо,8-ми дюймовий кольоровий сенсорний екран,6 динаміків,Bluetooth,управління на кермі
            -легкосплавні диски,шини 205/60R16
            -технологія MyKey
            -системи безпеки та охорони ABS,ESC,EBA,HLA,EPATS,PIB,TPMS
            -6 подушок безпеки
            -світлодіодні ліхтарі денного світла LED
            -підігрів передніх сидінь та обігрів лобового скла
            -спинка заднього сидіння,що складається окремо(60/40)
            -електропідйомники всіх вікон
            -регулювання рульової колонки за вильтом і висотою
            -центральний замок з пультом дистанційного управління
            -підігрів керма
            -датчик світла
            -передні протитуманні фари
            -сидіння водія з механічним регулюванням за 4 позиціями та поперековою опорою

            ...
        </description>
        <mileage>без пробега</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="16">
        <title>Ford Tourneo Custom 2.0 TDI AT F320 (130 л.с.) L2H1 2019</title>
        <price>42 368</price>
        <location>Житомир</location>
        <engine>Дизтопливо, 2.0 л.</engine>
        <description>без пробега Житомир Дизтопливо, 2.0 л. Автомат Ціна вказана з доплатою за колір.
            Комплектація:
            -системи безпеки та охорони:ABS,ESP,ROM,EBA,HLA,TC,TPMS
            -центральний замок з дистанційним керуванням
            -обладнання для холодного пуску -29
            -кондиціонер та обігрів у задній частині салону автомобіля
            -бортовий комп'ютер
            -гідропідсилювач керма
            -механічне регулювання кута нахилу фар
            -круїз-контроль з обмеженням швидкості
            -передні та задні датчики паркування
            -камера заднього виду
            -денні ходові вогні-LED
            -шини 215/60R16 на легкосплавних дисках
            -передні бризговики
            -передні протитуманні фари
            -радіо,8" сенсорний екран дисплей,10 динаміків,управління аудіо на кермі,Bluetooth,USB-роз'єми
            -шкіряне оздоблення керма
            -тканинне оздоблення сидінь
            -ліхтарі освітлення багажного відсіку
            -три окремі сидіння в другому ряді
            -бокові підлокітники 2-го ряду сидінь
            -підлокітник для сидіння водія та переднього пасажира
            -запасне колесо
            -тонування задніх вікон
            -датчик світла та дощу
            -бокові подушки безпеки для водія та переднього пасажира
            -підтримка попереку на сидінні водія


            ...
        </description>
        <mileage>без пробега</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="17">
        <title>Ford Escape 2017</title>
        <price>15 500</price>
        <location>Херсон</location>
        <engine>Бензин, 1.5 л.</engine>
        <description>20 тыс. км Херсон Бензин, 1.5 л. Автомат Предлагаю вашему вниманию отличный автомобиль. Авто было
            куплено в США. По карфаксу автомобиль начал свой жизненный путь 23 января 18 года. из повреждений был
            заменен только передний бампер и 1 фара которые приехали вместе с машиной в коробках от официалов с США.
            Небольшой пробег. 2 ключа. Любое сто на проверку. Делалась машина для себя.Торгуемся и забираем классный
            аппарат!!! ...
        </description>
        <mileage>20 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="18">
        <title>Ford Kuga New 1.5D AT (120 л.с.) 2019</title>
        <price>25 698</price>
        <location>Киев</location>
        <engine>Дизтопливо, 1.5 л.</engine>
        <description>без пробега Киев Дизтопливо, 1.5 л. Автомат Frozen White&#13;
            Економічний дизельний кросовер з автоматичною трансмісією за доступною ціною у Віннер Автомотів за адресою
            пр. Степана Бандери 24-д &#13;
            1.5 (120 к.с.) FWD ДИЗЕЛЬ AT6 &#13;
            Витрати пального: за містом (л/100 км) 4.3 комбінована траса (л/100 км) 5,0 у місті (л/100 км) 5.8
            Яскравий, надсучасний дизайн і стиль ззовні та всередині. Неперевершена динаміка та безумовна ефективність.
            Вражаючий перелік смарт-технологій, систем і функцій. І максимальна практичність, гнучкість та вигода — все,
            про що ви могли тільки мріяти. ...
        </description>
        <mileage>без пробега</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="19">
        <title>Ford Escape EcoBoost 16v 4WD 2016</title>
        <price>18 000</price>
        <location>Днепр (Днепропетровск)</location>
        <engine>Бензин, 1.5 л.</engine>
        <description>35 тыс. км Днепр (Днепропетровск) Бензин, 1.5 л. Автомат AE 6321 KT AUTO.RIA распознал гос.номер
            авто по фото 1FMCU9GDхHUхххх78 Проверено AUTO.RIA по реестрам МВД: дата последней операции, розыск,
            марка/модель, год, двигатель, цвет. Автомобиль в идеальном состоянии,с максимальной комплектацией,обслужен и
            ухожен не требует вложений,состояние нового авто. В салоне запах новой машины. 1FMCU9GD1HUB68678 Accessory 1
            USB Port-1 Remote Port Полир.металл.решетка С эл/прив.поднимаемой задн.двери Less - BTSI Manual Override
            Less Under Floor Stowage A Version Louisville Plant Built комплект спец. оборудования Модельный ряд Escape
            Тип кузова 5-дверный Вариант Номер базовой серии 2 Двигатель 1.5L EcoBoost 16V (180PS) Токсичность выхлопа
            Требов.к токсичн. выхлопа 50 State Коробка передач 6-ступенч. автомат. -6F Mid-Range Привод LHD 4WD (PTD)
            Передаточное число моста Передат.число главной передачи 3,51 Кондиционер А/С с двухзон. автом. темпер.контр.
            Возвр. стеклоочист. обогр. ветр.ст. Облицовка потолка Deluxe. С алюминиевыми внутр.ручками дверей Без сетки
            для удерживания багажа С напольн.ковр.покр.груз.отск. Less Lower Grille Молдинг ниж.обвязки контр.цв. С
            ярким молдингом рамы двери С наклон. зеркалом задн.вида Key-Integral Fob С формов. рукоят. рыч.перекл.пер. С
            замком с защ.от открыв.детьми С дист.упр.откр. задн.дв.баг.отд. Automatic Gearshift With Door Auto Relocking
            - Enabled Частота – 315 МГц С системой централ. запирания Keyless Entry - Illuminated Key Pad С переменн.
            прерыв.очисткой лоб.ст Фиксирующее крепление, вариант 2 Зап.кол."мини" стал.дис.17"х4.5 С 4 датчиками давл.в
            шинах Легкоспл.кол.диск 7,5х18" (Стиль 1) 235/50 R18 V Spare Tyre -T165/70R17 С центральн.орнам.ступицы-овал
            Ford С жалюзи радиатора Kysor Подогреватель блока цилиндров - SI6 Стартер - Система зап ...
        </description>
        <mileage>35 тыс. км</mileage>
        <transmission>Автомат</transmission>
    </element>
    <element id="20">
        <title>Ford Focus ОФІЦІЙНА - WINNER 2018</title>
        <price>11 500</price>
        <location>Стрый</location>
        <engine>Бензин, 1 л.</engine>
        <description>33 тыс. км Стрый Бензин, 1 л. Ручная / Механика Focus придбаний в 2018р. в офіційного дилера.
            За даний період накатала 33 тис. кілометрів
            Авто все в рідному окрасі.
            Стан нового авто, салон без цірапин

            ...
        </description>
        <mileage>33 тыс. км</mileage>
        <transmission>Ручная / Механика</transmission>
    </element>
</elements>